global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:3010']
  
  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
    scrape_interval: 1s
